[SASS-9316] Add logic for NICs Class 2 or Class 4 link
hmrc/income-tax-self-employment-frontend pull request #418
Opened 2024-08-07 20:49 UTC by Jake-Raffe

2024-08-09 08:37 UTC, Jake-Raffe commented on app/models/journeys/nics/TaxableProfitAndLoss.scala
> +  def returnClassTwoOrFourEligible(taxableProfitsAndLosses: List[TaxableProfitAndLoss], userDoB: LocalDate, taxYear: TaxYear): NicClassExemption = {
Separated this logic out of the view model so it can be reused for other pages

2024-08-09 08:37 UTC, Jake-Raffe commented on app/controllers/journeys/TaskListController.scala
>      handleResultT(result)
Tried to break up this huge for comprehension and make it a bit more descriptive

2024-08-09 15:13 UTC, lukastymo commented on app/models/journeys/nics/NicClassExemption.scala
> +case object Class2      extends NicClassExemption
can you put it inside NicsClassExcemption object? Usually they live in companion objects

2024-08-09 15:24 UTC, lukastymo commented on app/utils/TaxYearUtils.scala
> +object TaxYearUtils {
We can use `TaxYear`'s companion object for utility methods for `TaxYear`

2024-08-09 15:25 UTC, lukastymo commented on app/utils/TaxYearUtils.scala
> +  val dateNow = LocalDate.now()
That looks like a val (you probably wanted def) otherwise it will be constant until we restart the app.

2024-08-09 15:42 UTC, lukastymo requested changes
I'm not sure if the vals in TaxYearUtils were deliberately, also let's clarify if we want to use taxyear from the URL and inside TaxYear case class, or real current tax year (then it should probably go to companion  TaxYear object)

2024-08-12 11:33 UTC, Jake-Raffe commented on app/utils/TaxYearUtils.scala
> +  val currentTaxYearStartDate =
It replaces with the url taxyear in the ageIsBetween16AndStatePension method

2024-08-12 12:12 UTC, lukastymo approved these changes

2024-08-12 12:14 UTC, merged