SASS-8636 P&L:Adjusted taxable profit-create content page
hmrc/income-tax-self-employment-frontend pull request #432
Opened 2024-08-21 17:31 UTC by kuldeepwadhwa9

2024-08-22 10:09 UTC, Jake-Raffe commented on app/viewmodels/journeys/adjustments/AdjustedTaxableProfitSummary.scala
> +  def buildTable1(taxYear: TaxYear)(implicit messages: Messages): Table = {
Would rename this to `buildYourAdjustedProfitTable` rather than buildTable1. Same with all buildTables bellow.

2024-08-22 10:11 UTC, Jake-Raffe requested changes
Please can you add tests for the ViewModel, follow the format of other table viewmodels

2024-08-22 10:11 UTC, Jake-Raffe commented on app/controllers/journeys/adjustments/profitOrLoss/ProfitOrLossCalculationController.scala
> +    val summaryList               = SummaryListCYA.summaryListOpt(List())
Looks like summary list isn't doing anything in the controller or the view, can be removed?

2024-08-22 10:12 UTC, Jake-Raffe commented on app/controllers/journeys/adjustments/profitOrLoss/ProfitOrLossCalculationController.scala
> +    val adjustmentsTable          = buildTable5()
Do these changes need to also be represented in the ProfitOrLossCalculationControllerSpec?

2024-08-23 15:35 UTC, lukastymo approved these changes

2024-08-23 17:13 UTC, Jake-Raffe approved these changes

2024-08-27 08:38 UTC, merged